"""
Static site builder for the daily research briefing.

Reads every data/briefings/briefing_*.txt file and renders a small static HTML
site into docs/ (GitHub Pages serves straight from a docs/ folder on main, no
extra branch or build step needed).

This publishes RESEARCH NOTES, not trade recommendations:
  - no buy/sell calls, no personalized advice
  - no execution, no brokerage access, no live order path
  - every page carries the same disclaimer as the plain-text briefing

Run after generating a new briefing:
    python -m trading_agent.briefing_daily     # writes data/briefings/briefing_<date>.txt
    python -m trading_agent.publish_site       # rebuilds docs/
"""
from __future__ import annotations

import glob
import html
import os
import re
from datetime import date

HERE = os.path.dirname(__file__)
BRIEF_DIR = os.path.join(HERE, "data", "briefings")
SITE_DIR = os.path.join(HERE, "docs")

DISCLAIMER = (
    "This page is a research/informational summary, not a trade recommendation "
    "or investment advice. Figures come from an experimental, backtested-and-"
    "still-unproven paper-trading project. No orders are placed from this site. "
    "Nothing here is personalized to you. Do your own research before making any "
    "financial decision."
)

CSS = """
:root { color-scheme: light dark; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
       max-width: 780px; margin: 0 auto; padding: 24px 16px 64px; line-height: 1.5; }
header { margin-bottom: 24px; }
h1 { font-size: 1.4rem; margin-bottom: 4px; }
.subtitle { color: #666; font-size: 0.95rem; }
.disclaimer { background: #fff8e1; border: 1px solid #e0c46c; border-radius: 8px;
              padding: 12px 16px; font-size: 0.88rem; color: #5c4b00; margin-bottom: 28px; }
@media (prefers-color-scheme: dark) {
  .disclaimer { background: #3a2f00; border-color: #7a5c00; color: #f0d878; }
  .subtitle { color: #999; }
  a { color: #7ab8ff; }
}
pre.briefing { background: #f5f5f5; border-radius: 8px; padding: 16px; overflow-x: auto;
               font-size: 0.85rem; white-space: pre-wrap; word-wrap: break-word; }
@media (prefers-color-scheme: dark) { pre.briefing { background: #1e1e1e; } }
ul.history { list-style: none; padding: 0; }
ul.history li { padding: 8px 0; border-bottom: 1px solid #eee; }
@media (prefers-color-scheme: dark) { ul.history li { border-bottom-color: #333; } }
footer { margin-top: 40px; font-size: 0.8rem; color: #888; }
"""


def _page(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>{CSS}</style>
</head>
<body>
<header>
<h1><a href="index.html" style="text-decoration:none;color:inherit;">Daily Research Briefing</a></h1>
<div class="subtitle">{html.escape(title)}</div>
</header>
<div class="disclaimer">{html.escape(DISCLAIMER)}</div>
{body}
<footer>Generated by an automated research script. Not financial advice.</footer>
</body>
</html>
"""


def _briefing_files() -> list[tuple[str, str]]:
    """Return [(date_str, path), ...] sorted newest first."""
    out = []
    for path in glob.glob(os.path.join(BRIEF_DIR, "briefing_*.txt")):
        m = re.search(r"briefing_(\d{4}-\d{2}-\d{2})\.txt$", path)
        if m:
            out.append((m.group(1), path))
    out.sort(key=lambda t: t[0], reverse=True)
    return out


def build() -> None:
    os.makedirs(SITE_DIR, exist_ok=True)
    files = _briefing_files()

    if not files:
        raise SystemExit("No briefings found in data/briefings/. Run briefing_daily first.")

    # Per-day pages
    for day, path in files:
        text = open(path).read()
        body = f'<pre class="briefing">{html.escape(text)}</pre>'
        out_path = os.path.join(SITE_DIR, f"briefing_{day}.html")
        with open(out_path, "w") as f:
            f.write(_page(f"Briefing — {day}", body))

    # Index: latest briefing inline + history list
    latest_day, latest_path = files[0]
    latest_text = open(latest_path).read()
    history_items = "\n".join(
        f'<li><a href="briefing_{d}.html">{d}</a></li>' for d, _ in files
    )
    body = (
        f'<h2>Latest — {latest_day}</h2>'
        f'<pre class="briefing">{html.escape(latest_text)}</pre>'
        f'<h2>History</h2>'
        f'<ul class="history">{history_items}</ul>'
    )
    with open(os.path.join(SITE_DIR, "index.html"), "w") as f:
        f.write(_page(f"Latest: {latest_day}", body))

    # GitHub Pages: don't run this through Jekyll
    open(os.path.join(SITE_DIR, ".nojekyll"), "w").close()

    print(f"Built {len(files)} briefing page(s) -> {SITE_DIR}/")
    print(f"Preview locally: python3 -m http.server 8000 --directory {SITE_DIR}")


if __name__ == "__main__":
    build()
